[package]
name = "tun"
version = "0.1.0"
edition = "2024"

[lib]
name = "tun"
path = "src/lib.rs"

[[bin]]
name = "tun"
path = "src/bin/tun.rs"

[dependencies]
thiserror = "2.0"
net = { path = "../net" }
tokio = { version = "1.48", features = ["full", "rt-multi-thread", "tracing"] }
