[build]
rustflags = ["--cfg", "tokio_unstable"]
rustdocflags = ["--cfg", "tokio_unstable"]

[target.x86_64-unknown-linux-musl]
# Prefer static linking for all C deps when possible.
rustflags = ["--cfg", "tokio_unstable", "-C", "target-feature=+crt-static"]
